run:
  timeout: 10m
  allow-serial-runners: true

linters-settings:
  goimports:
    local-prefixes: github.com/datumforge/go-template
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
  revive:
    ignore-generated-header: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
    - wsl
issues:
  fix: true
  exclude-use-default: true
  exclude-dirs:
    - .buildkite/*
    - .github/*
    - docker/*
    - internal/ent/generated/*
  exclude-files:
    - internal/graphapi/gen_server.go
    - internal/graphapi/
    - internal/datumclient/graphclient.go
