env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  IMAGE_REPO: us-docker.pkg.dev/datum/${APP_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT:0:8}

steps:
- label: ":golangci-lint: lint :lint-roller:"
  key: "lint"
  plugins:
    - docker#v5.9.0:
        image: "registry.hub.docker.com/golangci/golangci-lint:v1.53-alpine"
        command: ["golangci-lint", "run", "-v", "--timeout", "5m"]

- label: ":test_tube: test"
  key: "test"
  plugins:
    - docker#v5.9.0:
        image: golang:1.21
        command: ["go", "test", "./..."]

- label: ":golang: build"
  key: "gobuild"
  artifact_paths: "bin/${APP_NAME}"
  plugins:
    - docker#v5.9.0:
        image: "golang:1.21"
        environment:
          - CGO_ENABLED=0
          - GOOS=linux
        command: ["go", "build", "-buildvcs=false", "-mod=mod", "-a", "-o", "bin/$APP_NAME"]
