# server settings
server:
  debug: true
  dev: true

  # tls settings
  tls:
    enabled: false

# db settings
db:
  debug: true
  driverName: libsql
  primaryDbSource: "file:template.db"
  multiWrite: false
