---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . -}}-config
  {{ $labels := include "common.tplvalues.merge" (dict "values" ( list .Values.api.commonLabels (include "common.labels.standard" .) ) "context" . ) }}
  labels: {{- include "common.tplvalues.render" ( dict "value" $labels "context" $) | nindent 4 }}   
  {{- if .Values.api.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.api.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  DATUM_REFRESH_INTERVAL: {{ .Values.datum.refresh_interval | 10m }}
  DATUM_SERVER_DEBUG: {{ .Values.datum.server.debug | false }}
  DATUM_SERVER_DEV: {{ .Values.datum.server.dev | false }}
  DATUM_SERVER_LISTEN: {{ .Values.datum.server.listen | ":1337" }}
  DATUM_SERVER_SHUTDOWN_GRACE_PERIOD: {{ .Values.datum.server.shutdown_grace_period | 10s }}
  DATUM_SERVER_READ_TIMEOUT: {{ .Values.datum.server.read_timeout | 15s }}
  DATUM_SERVER_WRITE_TIMEOUT: {{ .Values.datum.server.write_timeout | 15s }}
  DATUM_SERVER_IDLE_TIMEOUT: {{ .Values.datum.server.idle_timeout | 30s }}
  DATUM_SERVER_READ_HEADER_TIMEOUT: {{ .Values.datum.server.read_header_timeout | 2s }}
  DATUM_SERVER_TLS_ENABLED: {{ .Values.datum.server.tls.enabled | false }}
  DATUM_SERVER_TLS_CERT_FILE: {{ .Values.datum.server.tls.cert_file | "server.crt" }}
  DATUM_SERVER_TLS_CERT_KEY: {{ .Values.datum.server.tls.cert_key | "server.key" }}
  DATUM_SERVER_TLS_AUTO_CERT: {{ .Values.datum.server.tls.auto_cert | false }}
  DATUM_SERVER_CORS_ALLOW_ORIGINS: {{ .Values.datum.server.cors.allow_origins }}
  DATUM_SERVER_CORS_COOKIE_INSECURE: {{ .Values.datum.server.cors.cookie_insecure }}
  DATUM_DB_DEBUG: {{ .Values.datum.db.debug | false }}
  DATUM_DB_DATABASENAME: {{ .Values.datum.db.databaseName | "datum" }}
  DATUM_DB_DRIVERNAME: {{ .Values.datum.db.driverName | "libsql" }}
  DATUM_DB_MULTIWRITE: {{ .Values.datum.db.multiWrite | false }}
  DATUM_DB_PRIMARYDBSOURCE: {{ .Values.datum.db.primaryDbSource | "file:datum.db" }}
  DATUM_DB_SECONDARYDBSOURCE: {{ .Values.datum.db.secondaryDbSource | "file:backup.db" }}
  DATUM_DB_CACHETTL: {{ .Values.datum.db.cacheTTL | 1s }}
  DATUM_DB_RUNMIGRATIONS: {{ .Values.datum.db.runMigrations | true }}
  DATUM_DB_MIGRATIONPROVIDER: {{ .Values.datum.db.migrationProvider | "atlas" }}
  DATUM_REDIS_ENABLED: {{ .Values.datum.redis.enabled | true }}
  DATUM_REDIS_ADDRESS: {{ .Values.datum.redis.address | "localhost:6379" }}
  DATUM_REDIS_NAME: {{ .Values.datum.redis.name | "datum" }}
  DATUM_REDIS_USERNAME: {{ .Values.datum.redis.username }}
  DATUM_REDIS_PASSWORD: {{ .Values.datum.redis.password }}
  DATUM_REDIS_DB: {{ .Values.datum.redis.db | 0 }}
  DATUM_REDIS_DIALTIMEOUT: {{ .Values.datum.redis.dialTimeout | 5s }}
  DATUM_REDIS_READTIMEOUT: {{ .Values.datum.redis.readTimeout | 0 }}
  DATUM_REDIS_WRITETIMEOUT: {{ .Values.datum.redis.writeTimeout | 0 }}
  DATUM_REDIS_MAXRETRIES: {{ .Values.datum.redis.maxRetries | 3 }}
  DATUM_REDIS_MINIDLECONNS: {{ .Values.datum.redis.minIdleConns | 0 }}
  DATUM_REDIS_MAXIDLECONNS: {{ .Values.datum.redis.maxIdleConns | 0 }}
  DATUM_REDIS_MAXACTIVECONNS: {{ .Values.datum.redis.maxActiveConns | 0 }}
  DATUM_TRACER_ENABLED: {{ .Values.datum.tracer.enabled | false }}
  DATUM_TRACER_PROVIDER: {{ .Values.datum.tracer.provider | "stdout" }}
  DATUM_TRACER_ENVIRONMENT: {{ .Values.datum.tracer.environment | "development" }}
  DATUM_TRACER_STDOUT_PRETTY: {{ .Values.datum.tracer.stdout.pretty | true }}
  DATUM_TRACER_STDOUT_DISABLETIMESTAMP: {{ .Values.datum.tracer.stdout.disableTimestamp | false }}
  DATUM_TRACER_OTLP_ENDPOINT: {{ .Values.datum.tracer.otlp.endpoint | "localhost:4317" }}
  DATUM_TRACER_OTLP_INSECURE: {{ .Values.datum.tracer.otlp.insecure | true }}
  DATUM_TRACER_OTLP_CERTIFICATE: {{ .Values.datum.tracer.otlp.certificate }}
  DATUM_TRACER_OTLP_HEADERS: {{ .Values.datum.tracer.otlp.headers }}
  DATUM_TRACER_OTLP_COMPRESSION: {{ .Values.datum.tracer.otlp.compression }}
  DATUM_TRACER_OTLP_TIMEOUT: {{ .Values.datum.tracer.otlp.timeout | 10s }}
  DATUM_SESSIONS_SIGNINGKEY: {{ .Values.datum.sessions.signingKey | "my-signing-secret" }}
  DATUM_SESSIONS_ENCRYPTIONKEY: {{ .Values.datum.sessions.encryptionKey | "encryptionsecret" }}
