db:
    catchTTL: 0
    databaseName: ""
    debug: false
    driverName: ""
    multiWrite: false
    primaryDbSource: ""
    runMigrations: false
    secondaryDbSource: ""
ratelimit:
    burst: 0
    enabled: false
    expires: 0
    limit: 0
redis:
    address: ""
    db: 0
    dialTimeout: 0
    enabled: false
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 0
    minIdleConns: 0
    name: ""
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refresh_interval: 0
server:
    cacheControl:
        enabled: false
        etagHeaders: null
        noCacheHeaders: null
    cors:
        allowOrigins: null
        cookieInsecure: false
        enabled: false
        prefixes: null
    debug: false
    dev: false
    idle_timeout: 0
    listen: ""
    mime:
        defaultContentType: ""
        enabled: false
        mimeTypesFile: ""
    read_header_timeout: 0
    read_timeout: 0
    redirect:
        code: 0
        enabled: false
        redirects: null
    secure:
        contentsecuritypolicy: ""
        contenttypenosniff: ""
        cspreportonly: false
        enabled: false
        hstsmaxage: 0
        hstspreloadenabled: false
        referrerpolicy: ""
        xframeoptions: ""
        xssprotection: ""
    shutdown_grace_period: 0
    tls:
        auto_cert: false
        cert_file: ""
        cert_key: ""
        config: null
        enabled: false
    write_timeout: 0
sessions:
    encryptionKey: ""
    signingKey: ""
tracer:
    enabled: false
    environment: ""
    otlp:
        certificate: ""
        compression: ""
        endpoint: ""
        headers: null
        insecure: false
        timeout: 0
    provider: ""
    stdout:
        disableTimestamp: false
        pretty: false
