auth:
    enabled: true
    providers:
        github:
            clientEndpoint: http://localhost:17608
            clientId: ""
            clientSecret: ""
            redirectUrl: /v1/github/callback
            scopes: null
        google:
            clientEndpoint: http://localhost:17608
            clientId: ""
            clientSecret: ""
            redirectUrl: /v1/google/callback
            scopes: null
        redirectUrl: http://localhost:3001/api/auth/callback/datum
        webauthn:
            debug: false
            displayName: Datum
            enabled: true
            enforceTimeout: true
            maxDevices: 10
            relyingPartyId: localhost
            requestOrigin: http://localhost:3001
            timeout: 60000000000
    supportedProviders: null
    token:
        accessDuration: 3600000000000
        audience: https://datum.net
        generateKeys: true
        issuer: https://auth.datum.net
        jwksEndpoint: https://api.datum.net/.well-known/jwks.json
        keys: null
        kid: ""
        refreshAudience: ""
        refreshDuration: 7200000000000
        refreshOverlap: -900000000000
db:
    catchTTL: 1000000000
    databaseName: datum
    debug: false
    driverName: libsql
    enableHistory: false
    migrationProvider: atlas
    multiWrite: false
    primaryDbSource: file:datum.db
    runMigrations: true
    secondaryDbSource: file:backup.db
ratelimit:
    burst: 30
    enabled: false
    expires: 600000000000
    limit: 10
redis:
    address: localhost:6379
    db: 0
    dialTimeout: 5000000000
    enabled: true
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 3
    minIdleConns: 0
    name: datum
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refresh_interval: 600000000000
server:
    cors:
        allow_origins: null
        cookie_insecure: false
    debug: false
    dev: false
    idle_timeout: 30000000000
    listen: :1337
    read_header_timeout: 2000000000
    read_timeout: 15000000000
    shutdown_grace_period: 10000000000
    tls:
        auto_cert: false
        cert_file: server.crt
        cert_key: server.key
        config: null
        enabled: false
    write_timeout: 15000000000
sessions:
    encryptionKey: encryptionsecret
    signingKey: my-signing-secret
tracer:
    enabled: false
    environment: development
    otlp:
        certificate: ""
        compression: ""
        endpoint: localhost:4317
        headers: null
        insecure: true
        timeout: 10000000000
    provider: stdout
    stdout:
        disableTimestamp: false
        pretty: true
