db:
    catchTTL: 0
    databaseName: ""
    debug: false
    driverName: ""
    multiWrite: false
    primaryDbSource: ""
    runMigrations: false
    secondaryDbSource: ""
redis:
    address: ""
    db: 0
    dialTimeout: 0
    enabled: false
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 0
    minIdleConns: 0
    name: ""
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refresh_interval: 0
server:
    cors:
        allow_origins: null
        cookie_insecure: false
    debug: false
    dev: false
    idle_timeout: 0
    listen: ""
    read_header_timeout: 0
    read_timeout: 0
    shutdown_grace_period: 0
    tls:
        auto_cert: false
        cert_file: ""
        cert_key: ""
        config: null
        enabled: false
    write_timeout: 0
sessions:
    encryptionKey: ""
    signingKey: ""
tracer:
    enabled: false
    environment: ""
    otlp:
        certificate: ""
        compression: ""
        endpoint: ""
        headers: null
        insecure: false
        timeout: 0
    provider: ""
    stdout:
        disableTimestamp: false
        pretty: false
