db:
    catchTTL: 1000000000
    databaseName: datum
    debug: false
    driverName: libsql
    migrationProvider: atlas
    multiWrite: false
    primaryDbSource: file:datum.db
    runMigrations: true
    secondaryDbSource: file:backup.db
redis:
    address: localhost:6379
    db: 0
    dialTimeout: 5000000000
    enabled: true
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 3
    minIdleConns: 0
    name: datum
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refresh_interval: 600000000000
server:
    cors:
        allow_origins: null
        cookie_insecure: false
    debug: false
    dev: false
    idle_timeout: 30000000000
    listen: :1337
    read_header_timeout: 2000000000
    read_timeout: 15000000000
    shutdown_grace_period: 10000000000
    tls:
        auto_cert: false
        cert_file: server.crt
        cert_key: server.key
        config: null
        enabled: false
    write_timeout: 15000000000
sessions:
    encryptionKey: encryptionsecret
    signingKey: my-signing-secret
tracer:
    enabled: false
    environment: development
    otlp:
        certificate: ""
        compression: ""
        endpoint: localhost:4317
        headers: null
        insecure: true
        timeout: 10000000000
    provider: stdout
    stdout:
        disableTimestamp: false
        pretty: true
